### ISSUE TITLE
add ci integration

### ISSUE THREAD

**Issue by yutongp** [iotexproject/iotex-core-rosetta-gateway#18]
could be circle ci, could be github action. either is fine.
should check on both unit tests added in #17 and current e2e tests ran by `make test`

**Comment by raullenchai** [comment]
cc @JonSnow47

**Comment by dustinxie** [comment]
could use github Action to do ci testing
refer to https://github.com/iotexproject/iotex-address/commit/efcb81c838b88e98bae3583dd568dffd3786fd06
